name = "portfolio"
main = "worker/index.ts"
compatibility_date = "2025-01-01"

assets = { directory = "dist" }

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "b8370188-f60d-4ff4-8ee8-5cc4c03433ec"
migrations_dir = "drizzle/migrations"
